######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 3 16:17:53 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
RESOURCES += mainwindow.qrc
